### ISSUE TITLE
Images disappeared after upgrading to Podcast Generator 3

### ISSUE THREAD

**Issue by senarvi** [PodcastGenerator/PodcastGenerator#231] opened 2020-03-05 22:26 UTC
**System Information**
Podcast Generator Version: 3.0.1
Webserver: nginx 1.14.0
PHP Version: 7.2

**Podcast Generator Config**

```
I didn't manage to use the censorship tool.
``` 

**Description of your problem:**
I upgraded from 2.6 to 2.7, since it's apparently not possible to upgrade directly to 3. Everything was still working. Then I upgraded to 3.0.1. It seems to be working otherwise, but I don't see the episode images anymore.

I have the episode images in images directory. The xml files in media directory contain the name of the image file in an imgPG tag. Have you changed the location where the scripts look for the images in version 3?

Going through the settings I noticed a minor bug. The default theme is not visible on the Change Theme page, because theme.json lists PG version 3.0 only, and I now have 3.0.1.

In the web server error log I saw one error:
`No such file or directory in /var/www/mnt2/sugarcubes/core/freebox.php on line 15`
I just disabled the freebox for now, and didn't see any more error messages.

**Comment by emilengler** [comment] 2020-03-06 07:11
The problem is already know. I forgot to implement this when rewriting 3.0.
I'll plan to add this later. Maybe it will be included in 3.0.2 which is expected to be released in the next weeks. Otherwise in 3.1 which will be released on the 31th of May

**Closed by emilengler** 2020-03-06 07:11 UTC
Labels: Duplicate, Help Wanted
