### ISSUE TITLE
Cannot edit episodes.

### ISSUE THREAD

**Issue by ThomasLeigh** [PodcastGenerator/PodcastGenerator#266] opened 2020-05-07 13:13 UTC
**System Information**
Podcast Generator Version: 3.0.1
Webserver: InterServer
PHP Version: 7.1.33

**Expected behavior**
Successfully edited episode.

**Actual behavior**
Cannot edit episodes details. Once I click "Edit Episode", it reloads to default values (which have been obtained via FTP Feature, I guess).

**How to reproduce**
1. Index episodes via FTP Feature.
2. Edit an episode details.

**Comment by ThomasLeigh** [comment] 2020-05-07 13:56
I am not sure does this help, but the reason I use FTP indexing is that I haven’t been able to upload episodes by standard way: once uploading reached 100%, the page has been reloaded to the same form to begin upload an episode.

**Comment by ThomasLeigh** [comment] 2020-05-07 14:02
Related to https://github.com/PodcastGenerator/PodcastGenerator/issues/257 and https://github.com/PodcastGenerator/PodcastGenerator/issues/245 .

@emilengler 

> can you show me your permissions of the media directory?

rwxrwxrwx (0777)

**Comment by ThomasLeigh** [comment] 2020-05-07 14:53
I just discovered that it also does not allow changes within config.php . Even if I change it and upload the file - it all still remains unchanged within the admin panel. Config.php permissions: rw-r--r--

**Comment by emilengler** [comment] 2020-05-08 13:31
Is there something like an error log which you can post?

**Comment by ThomasLeigh** [comment] 2020-05-08 14:44
@emilengler  I will try to obtain those logs. In the meantime is there anything I could do? I have done a clean installation of PG, but to no avail. :( 

I’ve heard that May 31 may be a new PG release, could this help?

**Comment by emilengler** [comment] 2020-05-08 14:46
> @emilengler  I will try to obtain those logs. In the meantime is there anything I could do? I have done a clean installation of PG, but to no avail. :( 
> 
> 
> 
> I’ve heard that May 31 may be a new PG release, could this help?

As long as I cannot reproduce the issue I cannot gurantee that it will be fixed in 3.1. However it might be a good idea to add more informations on the screen like why this error occurs

**Comment by ThomasLeigh** [comment] 2020-05-08 14:47
>  it might be a good idea to add more informations on the screen like why this error occurs

Where I can find those information? I supposed You’ve talked about hosting logs?

**Comment by emilengler** [comment] 2020-05-08 15:15
> > it might be a good idea to add more informations on the screen like why this error occurs
> 
> Where I can find those information? I supposed You’ve talked about hosting logs?

Do you have shell access to your server?

**Comment by ThomasLeigh** [comment] 2020-05-08 15:17
I’m sorry, I don’t know :( I am not a haker like You ;) :)

**Comment by ThomasLeigh** [comment] 2020-05-08 15:44
What about this:

[08-May-2020 15:25:29 UTC] PHP Deprecated:  Function mcrypt_create_iv() is deprecated in /home/trailoft/public_html/audycje/Molium/update_pass.php on line 97
``

**Comment by ThomasLeigh** [comment] 2020-05-08 16:05
All the previous installations of PG I’ve done via Softacoelous App Installer. Now I’ve done this by hand, with the same result: cannot change anything within “Change Podcast Generator Configuration” section. config.php permissions rw-r--r-- (0644)

**Comment by emilengler** [comment] 2020-05-08 19:22
Ok, can you change the config.php permissions to rwxrwxrwx (0777)?
Not the best approach but it should do the job. A non saving config is mostly the result of invalid permissions

**Comment by ThomasLeigh** [comment] 2020-05-08 19:37
@emilengler I’ve already tried that one. Surprisingly enough, it does not help.

rwxrwxrwx (0777)

**Comment by ThomasLeigh** [comment] 2020-05-08 21:57
No error logs, unfortunately. There is only “molium.trailofthelight.xyz-ssl_log” full of POST and GET lines...

**Comment by computertalkradio** [comment] 2020-05-09 14:15
I am experiencing this same problem.  

\PHP_ERRORLOG contains a number of these per day:
[09-May-2020 07:58:10 CST6CDT] PHP Parse error:  syntax error, unexpected 'normal' (T_STRING) in /home/benjam66/public_html/computertalkradio.com/podcastCTR/config.php on line 81

\ADMIN\PHP_ERRORLOG contains:
[09-May-2020 08:57:28 CST6CDT] PHP Deprecated:  Function get_magic_quotes_runtime() is deprecated in /home/benjam66/public_html/computertalkradio.com/podcastCTR/components/getid3/getid3.php on line 299
[09-May-2020 08:57:30 CST6CDT] PHP Deprecated:  Function get_magic_quotes_runtime() is deprecated in /home/benjam66/public_html/computertalkradio.com/podcastCTR/components/getid3/getid3.php on line 299

**Comment by hallvors** [comment] 2020-05-10 21:50
I have uploaded MP3 files with FTP and indexed them. After editing, I land on a page saying the episode does not exist.. :o

**Comment by hallvors** [comment] 2020-05-10 22:00
Going from 
/index.php?name=2020-05-10-Oliver_Twist_kapittel_04.mp3
through edit button to
/admin/episodes_edit.php?name=2020-05-10-Oliver_Twist_kapittel_04.mp3
where I change the title (for some reason it has omitted "04") and change the date to an earlier one. Submitting redirects to
/index.php?name=2020-05-10-Oliver_Twist_kapittel_04.mp3
and it says "not found". The MP3 file still exists and so does the XML file next to it. Can I do anything more to help you get to the bottom of this problem?

**Comment by emilengler** [comment] 2020-05-11 09:42
Ok, I will have a deeper look at it soon

**Comment by emilengler** [comment] 2020-05-21 08:58
Can you give me the original mp3 and XML file so I can try to reproduce?

**Comment by ThomasLeigh** [comment] 2020-05-21 11:41
Here You are:

- [.mp3](https://trailofthelight.xyz/audycje/Molium/media/2020-05-21-Molium01.mp3)
- [.xml](https://trailofthelight.xyz/audycje/Molium/media/2020-05-21-Molium01.xml)

**Comment by emilengler** [comment] 2020-05-21 12:29
Thanks!

**Comment by Revbaw** [comment] 2020-05-25 19:44
Since update to 3 I can't edit previous episodes nor can I upload new ones.  I can only see 6 previous episodes. 
  Nor can I upload new ones.  It seems to upload the file fine but PodcastGenerator comes back with: "Invalid filename, only A-Z, a-z, underscores and dots are permitted".  Doesn't seem to matter what I name the file.  Even gave media directory 777 permissions...didn't help.

Where can I find version 2.7?  It was working for the last year without issue.

**Comment by emilengler** [comment] 2020-05-26 07:09
@Revbaw Do you have shell access to your web server?

**Comment by emilengler** [comment] 2020-05-26 10:17
@ThomasLeigh It's actually a feature, not a bug. Your XML file has no short description, nor is the explicit field set to yes or no. These two fields are required!

**Comment by Revbaw** [comment] 2020-05-26 19:02
> @Revbaw Do you have shell access to your web server?

yes full access.

**Comment by Revbaw** [comment] 2020-05-26 19:02
> @ThomasLeigh It's actually a feature, not a bug. Your XML file has no short description, nor is the explicit field set to yes or no. These two fields are required!

which xml file are you referring to?

**Comment by emilengler** [comment] 2020-05-26 21:19
Which operating system?

**Comment by ThomasLeigh** [comment] 2020-05-26 22:44
@emilengler 

> It's actually a feature, not a bug. Your XML file has no short description, nor is the explicit field set to yes or no. These two fields are required!

O my.... !!! Such a small thing and so much trouble. Thank You so so much, I’ve finally become able to start with my podcast hosted on my own server. I’m extremely happy that this is already possible.

The only remaining thing is “Change Podcast Generator Configuration” which I am not able to switch any of the three options from “Yes” to “No”. I mean, when I click “Submit”, it’s all becomes reverted to the original state. To change _config_ file permissions have not helped.

**Comment by emilengler** [comment] 2020-05-27 08:22
@ThomasLeigh Are you sure the values are not changed? Try to have a look at the config.php if they were changed.

When I wrote the config changer page I forgot to load the settings but they should still work AFAIK

**Comment by emilengler** [comment] 2020-05-27 08:29
Fixed this now!
Shouldn't be there in Podcast Generator 3.1

**Closed** 2020-05-27 08:29 UTC
Labels: Bug

**Comment by ThomasLeigh** [comment] 2020-05-27 12:18
@emilengler 

> Are you sure the values are not changed? Try to have a look at the config.php if they were changed.

Yes, it seems that the only thing that is not changed is the switch within the settings page.

**Comment by emilengler** [comment] 2020-05-27 12:32
I know that the settings page doesn’t display it but I am very sure it is changed in the config. Otherwise it must be a permission error

**Comment by ThomasLeigh** [comment] 2020-05-27 12:35
@emilengler 

And it’s like You said. I haven’t thought to check the results before, the switches have taken my attention ^^"

**Comment by emilengler** [comment] 2020-05-27 12:36
Glad to hear that it works :)

Your problem will be fixed on Sunday

**Comment by ThomasLeigh** [comment] 2020-06-02 20:31
@emilengler 

I’ve successfully added and edited almost all the episodes, with one stubborn exception so far. Nothing has helped. Finally I edited Title, Short Description and Author by hand, but I don’t know where I could edit date and time? And, moreover, why this particular episode is so stubborn :) ? If You’d be interested to have a look - here You are the .xml and .mp3 files (those links are not clickable via a standard Markdown, so I’ve pasted them the following way):

	https://trailofthelight.xyz/audycje/Molium/media/2020-05-07-Molium 37 - 01.2017.xml
 

	https://trailofthelight.xyz/audycje/Molium/media/2020-05-07-Molium 37 - 01.2017.mp3

**Comment by emilengler** [comment] 2020-06-02 22:18
> where I could edit date and time?

The date and time are is the file modification date, it is not set through the XML file

**Comment by ThomasLeigh** [comment] 2020-06-02 22:54
@emilengler Do You have any idea why I can’t edit a new date or time via the admin panel?

**Comment by ThomasLeigh** [comment] 2020-06-02 22:55
The both files of the stubborn episode have the same attributes as the files which are working fine.

**Comment by emilengler** [comment] 2020-06-02 22:56
> @emilengler Do You have any idea why I can’t edit a new date or time via the admin panel?

I think it is a fault of your hosting provider. Doesn’t your provider offers an online ftp tool where you can modify timestamös? Try this one

**Comment by ThomasLeigh** [comment] 2020-06-03 13:57
But in case of all the rest episodes I’ve been able to change date and time via the admin panel, therefore my confusion... This particular episode has the same file name pattern as the rest. But as a result nothing couldn’t be changed within the admin panel - regarding only this one episode.

I’ve checked Your advice with timestamps, thank You for Your will to help.

**Comment by emilengler** [comment] 2020-06-03 14:40
I think it is very likely to be a permission error

**Comment by emilengler** [comment] 2020-06-03 14:40
Your XML and mp3 file look both very normal and legitimate to me

**Comment by ThomasLeigh** [comment] 2020-06-03 14:47
I checked the permissions within my ftp client: all the files within “media” folder have the same permissions: rw-r--r-- (0644). I’ll try to re-upload the file...

**Comment by ThomasLeigh** [comment] 2020-06-03 15:03
I’ve re-uploaded the file with a name “Molium 37 - 01.2017.mp3” - now it works.
