### ISSUE TITLE
Episode player missing for some episodes

### ISSUE THREAD

**Issue by alwa** [PodcastGenerator/PodcastGenerator#201] opened 2020-01-19 11:00 UTC
I've upgraded from 2.7 to 3.0.
In the list of episodes some of them have a player with text such as:

"Filetype: MP3 - Size: 102,07 MB - Duration: 44:30m (320 kbps 44100 Hz)"

... while most of them don't. It looks like it could have something to do with file size. The largest episode that has a player is less than 200MB.

Could this be the cause? If so, how do I fix it?

**Comment by emilengler** [comment] 2020-01-19 14:12
Maybe it is because `max_upload_form_size` in config.php. Try to increase it

**Comment by alwa** [comment] 2020-01-19 17:50
@emilengler It didn't help I'm afraid

**Comment by emilengler** [comment] 2020-01-19 18:33
I will work on it tomorrow. I have tested version 3 good but not with files >50MB. I will do this now

**Comment by alwa** [comment] 2020-01-19 20:18
@emilengler Note that in 2.7 I had to upload files using an FTP client (and FTP automatic indexing) as the web application would not allow very big files

**Comment by dskeen** [comment] 2020-02-17 21:52
I am having the same problem even on a clean install.  and it does seem to be somewhat related to larger files. i have a 7mb mp3 that displays the metadata and the player just fine.  and i have a 56mb file that does not display any of that.  just FYI

**Comment by emilengler** [comment] 2020-02-18 19:22
> I am having the same problem even on a clean install. and it does seem to be somewhat related to larger files. i have a 7mb mp3 that displays the metadata and the player just fine. and i have a 56mb file that does not display any of that. just FYI

Can you give me a link to an episode where it is not working?
I believe it is because of the MIME type

**Comment by dskeen** [comment] 2020-02-18 20:18
Sure thing.  this is my test environment site.  http://david-keener.com/podcast
you can see all episodes there.  here is a specific one http://david-keener.com/podcast/index.php?name=2020-02-18-2-22-20.mp3

**Comment by emilengler** [comment] 2020-02-19 13:43
> Sure thing. this is my test environment site. http://david-keener.com/podcast
you can see all episodes there. here is a specific one http://david-keener.com/podcast/index.php?name=2020-02-18-2-22-20.mp3

I downloaded and inspected the file.
May it be possible that your mp3 file has a cover image?

**Comment by cmpilato** [comment] 2020-02-19 14:19
I can confirm that with the file as-is, PHP's `mime_content_type()` method considers the file to have an `application/octet-stream` type.  If I use the `id3v2` command-line tool to remove the `APIC` ID3v2 frame (the episode artwork), `mime_content_type()` reports the resulting file as being of type `audio/mpeg`.

**Comment by dskeen** [comment] 2020-02-19 14:58
> > Sure thing. this is my test environment site. http://david-keener.com/podcast
> > you can see all episodes there. here is a specific one http://david-keener.com/podcast/index.php?name=2020-02-18-2-22-20.mp3
> 
> I downloaded and inspected the file.
> May it be possible that your mp3 file has a cover image?
> If so, remove the cover image and try it again. Currently PG does not support Cover Images.
> Will fix this in the next release however

it looks like that might have done the trick.  I removed the album art from all files, re-uploaded them and now i have the file data as well as the embedded player. Thanks for the info.

**Comment by cmpilato** [comment] 2020-02-19 16:31
For what it's worth, I suspect that the root of the problem is almost certainly _not_ that PodcastGenerator itself doesn't support episode artwork.  It's that the lower-level mechanism that PHP uses to identify file content types makes some assumptions, such as assuming that the MP3 identifying "magic" bytes appear somewhere in first so many bytes of the file.  Removing the APIC frame merely allows the MP3 audio header and stream to have an offset in the file closer to the beginning, increasing the chances of the file magic parser finding it and declaring with confidence, "Yup, this is an MPEG audio layer 3 file!"

I _suspect_ that if these files had smaller artwork (the image data was 1.5 Mbytes long in the file I looked at, as shown below), `mime_content_type()` might succeed in identifying the file as an `audio/mpeg`.  @dskeen Are you able to verify that theory?

```
Filename: 2020-02-18-2-22-20.mp3
TPE1: Pastor Ron Heasley
TIT2: Saturday February 22, 2020
TYER: 2020
TXXX: (PRODUCER): David Keener
APIC: ()[, 3]: image/jpeg, 1445079 bytes
```

**Comment by dskeen** [comment] 2020-02-19 16:35
> For what it's worth, I suspect that the root of the problem is almost certainly _not_ that PodcastGenerator itself doesn't support episode artwork. It's that the lower-level mechanism that PHP uses to identify file content types makes some assumptions, such as assuming that the MP3 identifying "magic" bytes appear somewhere in first so many bytes of the file. Removing the APIC frame merely allows the MP3 audio header and stream to have an offset in the file closer to the beginning, increasing the chances of the file magic parser finding it and declaring with confidence, "Yup, this is an MPEG audio layer 3 file!"
> 
> I _suspect_ that if these files had smaller artwork (the image data was 1.5 Mbytes long in the file I looked at, as shown below), `mime_content_type()` might succeed in identifying the file as an `audio/mpeg`. @dskeen Are you able to verify that theory?
> 
> ```
> Filename: 2020-02-18-2-22-20.mp3
> TPE1: Pastor Ron Heasley
> TIT2: Saturday February 22, 2020
> TYER: 2020
> TXXX: (PRODUCER): David Keener
> APIC: ()[, 3]: image/jpeg, 1445079 bytes
> ```

Im afraid you are WAY above my paygrade on that info.  all i know is that this worked just fine in PG 2.7 and it doesnt work now in PG 3.0.1.  exact same mp3 files uploaded into both versions of PG (2.7 and 3.0.1) produce different results.  thats all I know.

**Comment by cmpilato** [comment] 2020-02-19 16:58
Sorry.  I guess to ask it more clearly, I was wondering if using smaller episode artwork (the "picture" found in the MP3's ID3 metadata tag) would allow the file to be detected as an audio file (rather than as a generic collection of bytes that could be anything).  So I just downloaded EasyTag, and used it to replace the picture in your episode with a smaller one (only about 0.5 Mb), and it seems that now that MP3 file is identified as `audio/mpeg` -- a valid audio file.

I'm not sure why PG3.0 doesn't handle your file correctly.  If PG2.7 did, then I suspect we shouldn't be closing this issue and should instead treat this as a regression bug.  Maybe PG2.7 looked only at the file extension (`.mp3`) instead of trying to calculate the content type?  Not sure.

**Comment by emilengler** [comment] 2020-02-19 17:06
Ok will re-open this and invest my weekend into PG :)
There is still a lot to do and I'm sorry if the bugs in PG 3.0 might lead you to switch back.
However I will try my best to fix all the bugs and make 3.1 much better :rocket:

**Comment by dskeen** [comment] 2020-02-19 17:12
> Ok will re-open this and invest my weekend into PG :)
> There is still a lot to do and I'm sorry if the bugs in PG 3.0 might lead you to switch back.
> However I will try my best to fix all the bugs and make 3.1 much better 🚀

no worries at all!  I for one and very happy to see that PG is not dead, but is being revived and worked on and will continue to improve!  if i need to wait a few months to upgrade in order to get the functionality I want. i am perfectly fine with that!  Thank you for your efforts and your work!

**Comment by emilengler** [comment] 2020-04-30 10:08
Sorry I cannot reproduce this. Can you give me the mp3 file you used? @alwa

**Comment by alwa** [comment] 2020-05-01 10:53
@emilengler This one for example: http://salongsberusadhistoria.champagneklubben.com/media/2019-06-28_fem_ser_rott.mp3

**Comment by emilengler** [comment] 2020-05-02 06:32
> For what it's worth, I suspect that the root of the problem is almost certainly _not_ that PodcastGenerator itself doesn't support episode artwork. It's that the lower-level mechanism that PHP uses to identify file content types makes some assumptions, such as assuming that the MP3 identifying "magic" bytes appear somewhere in first so many bytes of the file. Removing the APIC frame merely allows the MP3 audio header and stream to have an offset in the file closer to the beginning, increasing the chances of the file magic parser finding it and declaring with confidence, "Yup, this is an MPEG audio layer 3 file!"
> 
> I _suspect_ that if these files had smaller artwork (the image data was 1.5 Mbytes long in the file I looked at, as shown below), `mime_content_type()` might succeed in identifying the file as an `audio/mpeg`. @dskeen Are you able to verify that theory?
> 
> ```
> Filename: 2020-02-18-2-22-20.mp3
> TPE1: Pastor Ron Heasley
> TIT2: Saturday February 22, 2020
> TYER: 2020
> TXXX: (PRODUCER): David Keener
> APIC: ()[, 3]: image/jpeg, 1445079 bytes
> ```

You were right, it is indeed a low level bug. I use a getID3 function for getting the mime type now. It works much better even with cover arts

**Comment by emilengler** [comment] 2020-05-21 08:58
@alwa The file you provided works perfectly in the PG 3.1 "snapshot"
It'll probably be fixed with that version expected on the 31th of May

**Closed by emilengler** 2020-05-21 08:58 UTC
Labels: Bug
