### ISSUE TITLE
Scheduled posts not working (i am not sure)

### ISSUE THREAD

**Issue by thadeu220** [PodcastGenerator/PodcastGenerator#449] opened 2021-12-14 18:48 UTC
Hello.
if i schedule a post to december, 25th, 2021, i mean, future time, the podcast episode are not shown for editing.
So if i want to reschedule it, it will not be possible.

in the media folder, the xml file of the scheduled episode shows the time of the posting date, not future date:

Steps to reproduce::

1. install podcast generator and setup
2. add a new episode (today date)
3. Add a new episode in future time.
4. run the recreate feed function using wget, curl or manual
5. the scheduled post will disappear from the episodes menu, and i will not be able to edit it, and i am not sure if it will be posted or not.

Expected behavior:
show the scheduled episode in the edit episodes tab in admin, allowing me to do further modifications.

How can i make sure that it will be posted in december 25th 2021?
i already activated crontab with: wget https://podcasts.mytestingwebsite.com/pg-cron.php?key=Fp8Y0gRh

**System Information**
Podcast Generator Version: 3.1.2
Webserver: litespeed
PHP Version: 7.4.13

**Comment by coldacid** [comment] 2021-12-14 18:52
Duplicate of #445

**Closed** 2021-12-14 18:52 UTC
Labels: Bug, Duplicate
