### ISSUE TITLE
scheduling an episode makes it completely disappear

### ISSUE THREAD

**Issue by dskeen** [PodcastGenerator/PodcastGenerator#287] opened 2020-06-18 16:54 UTC
**System Information**
Podcast Generator Version: 3.1
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

It used to be that when you would schedule an episode for a future release date, it would stay visible on the admin side but disappear on the public side until the scheduled date and time

now when i schedule a podcast for a future date and time, it disappears completely from everywhere. both the admin side as well as public side.  and after i change the date and time i get a page that says "Episode does not exist"

i have no idea if it will show up at the expected date and time because i havent reached that time yet. i suppose i will have to wait and see.

**Comment by emilengler** [comment] 2020-06-18 17:45
> i have no idea if it will show up at the expected date and time because i havent reached that time yet. i suppose i will have to wait and see.

It will!
This is feature not a bug. If someone ones to work on a features which displays episodes in future in the admin area I would accept such a PR

**Comment by ryangurn** [comment] 2020-06-21 04:25
@dskeen so the podcasts scheduled for the future do not show in the admin area?

**Comment by dskeen** [comment] 2020-06-21 04:30
That’s correct. Once you schedule it, it cannot be seen anywhere. So you have no way of making sure you selected the right date and time.

Sent from my iPhone

On Jun 21, 2020, at 12:26 AM, Ryan Gurnick <notifications@github.com> wrote:

﻿

@dskeen<https://github.com/dskeen> so the podcasts scheduled for the future do not show in the admin area?

**Comment by emilengler** [comment] 2020-06-21 09:01
> That’s correct. Once you schedule it, it cannot be seen anywhere. So you have no way of making sure you selected the right date and time.

You can! The time is being fetched from the last modified time by the operating system. You can go to the media/ directory to see it.

**Comment by kalvinmattheus** [comment] 2020-06-21 11:53
#290 will solve this bug.

**Comment by emilengler** [comment] 2020-07-02 09:21
Fixed with #290

**Closed by emilengler** 2020-07-02 09:21 UTC
Labels: Bug
