### ISSUE TITLE
Regression: Cover art no longer shown per episode

### ISSUE THREAD

**Issue by alwa** [PodcastGenerator/PodcastGenerator#198] opened 2020-01-18 14:31 UTC
In 2.7 it was possible (although hacky) to set cover art per episode: https://github.com/albertobeta/PodcastGenerator/issues/30

After upgrade these covers are no longer shown.

**Comment by emilengler** [comment] 2020-01-18 14:40
Currently PG 3 gets only bitrate, frequency and length as mp3 metadata information.
I will adjust this tomorrow. Sunday will probably become my PG day of the week

**Comment by damiencarol** [comment] 2020-02-23 14:31
Same here, we are in 2.5 and want to migrate to 3.0.

**Comment by ryangurn** [comment] 2020-03-23 07:21
According to https://help.apple.com/itc/podcasts_connect/#/itcb54353390 we can use `itunes:image` within the `item` object for the RSS. The fun part of this is that we will need to find a way to upload and keep track of each image file for each specific podcast episode. 

This is relatively easy to just throw together however just to be sure that we are all on the same page, the feature desired is to be able to upload a different image for **each** podcast if desired, correct?

**Comment by emilengler** [comment] 2020-03-23 10:39
The problem is less the iTunes Tag, the problem is more the way to extract the audio cover

**Comment by emilengler** [comment] 2020-03-23 10:40
I think it is possible with getID3 (the lib we use for mp3 metadata) but I haven't got myself into it that much

**Comment by ryangurn** [comment] 2020-03-23 17:38
do we want to extract it from the mp3 or just ask that the user upload a jpg along with the mp3 file?

**Comment by emilengler** [comment] 2020-03-23 17:39
First one, this was the way 2.7 handled it

**Comment by ryangurn** [comment] 2020-03-23 17:41
ok sounds good, I will look into the source for 2.7 and see if I can match that feature in 3.1. was there a specific subroutine that this was intended to be run in?

**Comment by kldudeck** [comment] 2020-03-23 22:01
I am having the same issue - cover art not appearing when uploaded via FTP. This happened about 3 weeks ago and for the life of me, I have no idea how I made it appear in the previous episode. 
mudcatblues.com/podcast

**Comment by damiencarol** [comment] 2020-04-06 14:53
@ryangurn @emilengler I can confirm that the 2.7 allowed to upload a file **for each** podcast and we use it.

**Comment by emilengler** [comment] 2020-04-06 14:54
I'm already working on a patch by the way

**Comment by emilengler** [comment] 2020-04-26 09:53
Good news, it is now possible to select a image when setting it inside the <imgPG> tag in the specific XML file.
694e7ea2b69a53137f97c186444a8fa745e14961

I will now add a feature that PG extracts the images from the mp3 files automatically.

**Comment by emilengler** [comment] 2020-04-26 18:43
Ok just finished the patch :-)
Will be released with version 3.1 expected to arrive on 31th of May

**Closed** 2020-04-26 18:42 UTC
Labels: Bug
