### ISSUE TITLE
Add the ability to change podcast album art

### ISSUE THREAD

**Issue by Invictaz** [PodcastGenerator/PodcastGenerator#159] opened 2019-12-31 14:29 UTC
Allow custom album art per podcast episode

Also, change the album art of a lot of episodes at once.

**Comment by emilengler** [comment] 2019-12-31 15:27
I like the idea, really. But as far as I know this is impossible because Podcast Readers want a global image for the entire podcast. You can also see this in the feed.xml. The `itunes:image` is only declared in the header of the document

**Comment by Invictaz** [comment] 2019-12-31 16:43
This is not true on several podcasts as they have even different images *inside* a podcast. Maybe it's a vodcast then. Not sure. Not M4A audio but different format. Each song has it's own artist cover.

**Comment by emilengler** [comment] 2019-12-31 17:30
Ok will take a deeper look at it

**Comment by cmpilato** [comment] 2020-01-02 15:21
Maybe change the description of this issue to read:  "Add the ability to configure episode artwork" ?  (The word "episide" will help this stand out as not referring to the artwork for the podcast as a whole.)

**Comment by alwa** [comment] 2020-01-18 16:05
It is/was possible to set per episode: https://github.com/albertobeta/PodcastGenerator/issues/30

I reported this missing feature as a regression here: https://github.com/albertobeta/PodcastGenerator/issues/198

**Comment by emilengler** [comment] 2020-04-29 11:24
I added this for 3.1 a few days ago. Will be released on 31th of May this year.
A bulk change of all episode covers is probably better done with an external script. If there is need for it I can write one

**Closed by emilengler** 2020-04-29 11:24 UTC
